name: Unity Edit Mode Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Edit Mode Tests for CarTest
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache Unity packages
      - name: Cache Unity packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/unity3d
          key: ${{ runner.os }}-unity-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-unity-

      # Install Unity Editor
      - name: Install Unity
        uses: game-ci/unity-installer@v3
        with:
          version: 2021.3.40f1

      # Run Unity Edit Mode Tests for CarTest
      - name: Run Unity Edit Mode Tests
        uses: game-ci/unity-test-runner@v3
        with:
          version: 2021.3.40f1
          testMode: editmode
          customParameters: -testFilter=CarTest.GetNoDoors_Test,CarTest.SetNoDoors_Test
